### ISSUE TITLE
Не получается запустить

### ISSUE THREAD

**Issue by mishailovic** [khoben/telemirror#1]
Так и не получилось запустить код, если не сложно сделай инструкцию для чайников. Через 9 дней удаляют мой любимый канал по причине неактива его автора. Нужно срочно его отзеркалить.

**Comment by khoben** [comment]
Изначально это приложение сделано для копирования новых сообщений, но
я так понимаю нужно все посты с одного канала скопировать в другой? В таком случае добавил [файлик](https://github.com/khoben/telemirror/blob/master/telecopy.py). Запускать также как описал в [README](https://github.com/khoben/telemirror/blob/master/README.md), только в конце python telecopy.py.

**Comment by mishailovic** [comment]
> Изначально это приложение сделано для копирования новых сообщений, но
> я так понимаю нужно все посты с одного канала скопировать в другой? В таком случае добавил [файлик](https://github.com/khoben/telemirror/blob/master/telecopy.py). Запускать также как описал в [README](https://github.com/khoben/telemirror/blob/master/README.md), установить в файле telecopy.py SESSION_STRING SOURCE_CHAT TARGET_CHAT и запустить его.

Огромное спасибо! Иссью закрываю.
