### ISSUE TITLE
Пропуски при копировании. 

### ISSUE THREAD

**Issue by T4eslenko** [khoben/telemirror#101]
Привет, спасибо еще раз за программу. Столкнулся, что программа может рандрмно пропускать посты при копировании в каналы. В чем может быть дело, куда копать? Крутиться в докере на виртуалке. Оперативной памяти и мощности проца судя по графикам хватает. Спасибо

**Comment by khoben** [comment]
Зависит от логики рассылки обновлений Telegram. Попробуй создать новую сессию, сменить ip или сам аккаунт.

**Comment by wftutorial** [comment]
fasdfas
