### ISSUE TITLE
Фильтр сообщений с каналов

### ISSUE THREAD

**Issue by T4eslenko** [khoben/telemirror#106]
Привет. Спасибо еще раз з программу. Сейчас собираю сообщения с чатов, возникла необходимость отсеивать (не пересылать) репосты с публичных каналов. Каким образом это можно сделать? Заранее спасибо за ответ

**Comment by khoben** [comment]
Нужен фильтр, который возвращает `False, message`, если сообщение является репостом с канала. Узнать это можно из переменной `message.fwd_from`. Попробуй посмотреть документацию как определить, что это именно репост с канала https://core.telegram.org/constructor/messageFwdHeader и залогировать при каких параметрах нужно отсеивать сообщения.

**Comment by T4eslenko** [comment]
надо новый фильтр написать или дописать к существующему?
Допустим, пересылку с канала можно так отлавливать
fwd_channel = message.fwd_from.from_id.channel_id if isinstance(message.fwd_from, MessageFwdHeader) and hasattr(message.fwd_from.from_id, 'channel_id') and isinstance(message.fwd_from.from_id, PeerChannel) else None
