### ISSUE TITLE
Exception when message received

### ISSUE THREAD

**Issue by mehtadone** [khoben/telemirror#109]
Anyone got any thoughts on why this maybe?

```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\web_protocol.py", line
350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp\\_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01'
      ^
Error handling request
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\web_protocol.py", line
350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp\\_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'nil'
      ^
```

**Comment by khoben** [comment]
> Anyone got any thoughts on why this maybe?
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\web_protocol.py", line
> 350, in data_received
>     messages, upgraded, tail = self._request_parser.feed_data(data)
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "aiohttp\\_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
> aiohttp.http_exceptions.BadStatusLine: 400, message:
>   Invalid method encountered:
> 
>     b'\x16\x03\x01'
>       ^
> Error handling request
> Traceback (most recent call last):
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\web_protocol.py", line
> 350, in data_received
>     messages, upgraded, tail = self._request_parser.feed_data(data)
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "aiohttp\\_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
> aiohttp.http_exceptions.BadStatusLine: 400, message:
>   Invalid method encountered:
> 
>     b'nil'
>       ^
> ```

Can you show the full stacktrace of the error?

Actually `aiohttp` here is a health/ping endpoint over http. Telegram client works in parallel using the mtproto protocol.

**Comment by mehtadone** [comment]
This is all that is logged: ```Using database: InMemoryDatabase

INFO  2024-06-10 22:07:36,485 [mirroring.py:631]:telemirror: Logged in as md (447811004645)
Error handling request
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\web_protocol.py", line
350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp\\_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Pause on PRI/Upgrade:

    b''
      ^
Error handling request
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\web_protocol.py", line
350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp\\_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01'
      ^
```

**Comment by khoben** [comment]
This means someone is sending incorrect requests to the `/` address, this should not affect the client in any way. I didn't see in the logs that this exception occurs when a message is received.

You can comment out the line https://github.com/khoben/telemirror/blob/master/main.py#L53

**Comment by mehtadone** [comment]
Thank you @khoben
