### ISSUE TITLE
Бан аккаунта про login.py

### ISSUE THREAD

**Issue by qtozdec** [khoben/telemirror#113]
Просрочилась сесссия, сделал вновь login.py и получил моментальный бан. Завёл новый аккаунт - также бан. Политика телеграма изменилась?

**Comment by qtozdec** [comment]
В issues telethon предлагают следующее:
https://github.com/LonamiWebs/Telethon/issues/4051#issuecomment-1491747149

**Comment by khoben** [comment]
> В issues telethon предлагают следующее:
> https://github.com/LonamiWebs/Telethon/issues/4051#issuecomment-1491747149

Нет определенного решения этой проблемы. Из-за спамеров и ещё некоторых факторов, аккаунты рискуют попасть в бан.

Если способ с указанием версии действительно поможет, напиши об этом здесь, сделаю дополнительную конфигурацию клиента через yaml файл.

**Comment by qtozdec** [comment]
> Если способ с указанием версии действительно поможет, напиши об этом здесь, сделаю дополнительную конфигурацию клиента через yaml файл.

Плохо разбираюсь в python коде. Вижу, что используется более сложный механизм, чем явное указание TelegramClient('my_session', api_id, api_hash, system_version="4.16.30-vxCUSTOM"), поэтому вряд ли смогу сделать сам. По поводу блокировки - немного поспешил, на самом деле просто происходит полный logout со всех устройств, при попытке входа просит указать почту, введя код с которой выходит ошибка на подобии "Incorrect email_code" (точно не помню). Спустя половину суток код дал ввести. Вы пробовали заново создать сессию? Моя ошибка не воспроизвелась?

**Comment by khoben** [comment]
Вот тут можно добавить https://github.com/khoben/telemirror/blob/master/telemirror%2Fmirroring.py#L678

Это ошибка не относится конкретно к коду или к библиотеке telethon, а имеет значение совокупность факторов - ip, регион, номер, дата регистрации и прочее. На одном из аккаунтов с двух факторной аутентификацией также выходит со всех устройств на этапе первого обращения к API после получения сессии.
