### ISSUE TITLE
stops forwarding from the news channel

### ISSUE THREAD

**Issue by kvinstar** [khoben/telemirror#116]
So there is a news channel channel1 from where I configured forwarding to my test2 channel and added some filters, I first checked on my two channels test1 > test2 forwarding works, filters work correctly. Then I configured forwarding from channel1, it forwarded for a while, then it stopped, and I thought that the problem was in the filters, but when I copied from the channel1 to my test1 channel from where I also configured forwarding to test2, they were forwarded.
In other words, something is going on, the work is not stable. One and the same text from channel1 is not forwarded to test2, but from test1 to test2 is forwarded.
Maybe you can modify the script a little bit, so that it would be possible to use userbot user account in addition to bot.
chatgpt said
The bot can read messages, but with the limitations of Telegram's API for regular users.
Messages may be delayed or skipped due to frequency restrictions on requests.
Possible solutions:
Using a user account:
A user account (userbot) can be used instead of a bot.
This will allow you to subscribe to the channel and read messages, but may violate Telegram's terms of use.

**Comment by khoben** [comment]
😄 chatgpt said, it is better to trust the generated text with semantically similar phrases a little less

This already working with userbot. The problem is in the optimization of the Telegram servers resources, the server stops sending updates for some channels. Try restarting, getting a new session or IP.
