### ISSUE TITLE
Restricted filter not working with groups or topics

### ISSUE THREAD

**Issue by bratcorpse** [khoben/telemirror#123]
The restricted filter is working fine with channels but it isn't working with groups or topics

**Comment by khoben** [comment]
Hi, @bratcorpse 
Can you provide logs and `restricted filter` code?

**Comment by bratcorpse** [comment]
sorry for the late response, it's forwarding text but not attachments

INFO  2024-08-27 06:08:36,843 [mirroring.py:71]:telemirror: [New message]: https://t.me/c/2182848314/7
ERROR 2024-08-27 06:08:37,117 [mirroring.py:165]:telemirror: Error while sending message to chat#-1001596234020. ChatForwardsRestrictedError: You can't forward messages from a protected chat (caused by SendMediaRequest)
INFO  2024-08-27 06:08:48,786 [mirroring.py:71]:telemirror: [New message]: https://t.me/c/2182848314/8
INFO  2024-08-27 06:10:40,369 [mirroring.py:71]:telemirror: [New message]: https://t.me/c/2182848314/9
ERROR 2024-08-27 06:10:40,474 [mirroring.py:165]:telemirror: Error while sending message to chat#-1001596234020. ChatForwardsRestrictedError: You can't forward messages from a protected chat (caused by SendMediaRequest)

`from typing import Tuple, Type
from telethon import types

from ..hints import EventMessage, EventLike
from .base import MessageFilter


class RestrictSavingContentBypassFilter(MessageFilter):
    def __init__(self, send_restricted_content=True):
        self.send_restricted_content = send_restricted_content

    async def _process_message(
        self, message: EventMessage, event_type: Type[EventLike]
    ) -> Tuple[bool, EventMessage]:
        if message.chat.noforwards and message.media:
            # Handle images
            if isinstance(message.media, types.MessageMediaPhoto):
                client: TelegramClient = message.client
                photo: bytes = await client.download_media(message=message, file=bytes)
                cloned_photo: types.TypeInputFile = await client.upload_file(photo)
                message.media = cloned_photo
            # Others media types set to None (remove from original message)...
            else:
                message.media = None

        return True, message
`
this is the restrictedfilter.py which i'm using

**Comment by khoben** [comment]
> sorry for the late response, it's forwarding text but not attachments
> 
> INFO  2024-08-27 06:08:36,843 [mirroring.py:71]:telemirror: [New message]: https://t.me/c/2182848314/7
> ERROR 2024-08-27 06:08:37,117 [mirroring.py:165]:telemirror: Error while sending message to chat#-1001596234020. ChatForwardsRestrictedError: You can't forward messages from a protected chat (caused by SendMediaRequest)
> INFO  2024-08-27 06:08:48,786 [mirroring.py:71]:telemirror: [New message]: https://t.me/c/2182848314/8
> INFO  2024-08-27 06:10:40,369 [mirroring.py:71]:telemirror: [New message]: https://t.me/c/2182848314/9
> ERROR 2024-08-27 06:10:40,474 [mirroring.py:165]:telemirror: Error while sending message to chat#-1001596234020. ChatForwardsRestrictedError: You can't forward messages from a protected chat (caused by SendMediaRequest)
> 
> `from typing import Tuple, Type
> from telethon import types
> 
> from ..hints import EventMessage, EventLike
> from .base import MessageFilter
> 
> 
> class RestrictSavingContentBypassFilter(MessageFilter):
>     def __init__(self, send_restricted_content=True):
>         self.send_restricted_content = send_restricted_content
> 
>     async def _process_message(
>         self, message: EventMessage, event_type: Type[EventLike]
>     ) -> Tuple[bool, EventMessage]:
>         if message.chat.noforwards and message.media:
>             # Handle images
>             if isinstance(message.media, types.MessageMediaPhoto):
>                 client: TelegramClient = message.client
>                 photo: bytes = await client.download_media(message=message, file=bytes)
>                 cloned_photo: types.TypeInputFile = await client.upload_file(photo)
>                 message.media = cloned_photo
>             # Others media types set to None (remove from original message)...
>             else:
>                 message.media = None
> 
>         return True, message`
> 
> this is the restrictedfilter.py which i'm using
> 
> 
> 
> 

 Check that filter was added to `mirror.config.yml`. Here is sample working implementation for such filter - https://github.com/khoben/telemirror/issues/68#issuecomment-2131271737

**Comment by bratcorpse** [comment]
Thank you, photos are working not but it's not sending videos

**Comment by khoben** [comment]
> Thank you, photos are working not but it's not sending videos

Yep, you can handle other types:

```python
...
elif isinstance(message.media, types.MessageMediaDocument):
    client: TelegramClient = message.client
  
    downloaded_media: bytes = await client.download_media(
        message=message, file=bytes
    )
    cloned_media_file: types.TypeInputFile = await client.upload_file(
        downloaded_media
    )
  
    cloned_media = types.InputMediaUploadedDocument(
        file=cloned_media_file,
        mime_type=message.media.document.mime_type,
        attributes=message.media.document.attributes,
        spoiler=message.media.spoiler,
        ttl_seconds=message.media.ttl_seconds,
    )
  
    message.media = cloned_media
else:
...
```
I think it's also a good idea to check the maximum size for the file, RAM might not be enough for big files:
```python
if message.file and message.file.size > self._max_file_size_bytes:
    # File too big
    return False, message
```
Or even re-upload from the filesystem.

**Comment by bratcorpse** [comment]
Thank you for the help, really appreciate it <3!!
