### ISSUE TITLE
make find & replace filter for exceptions & must have/not value found for mirror permission

### ISSUE THREAD

**Issue by claimclone** [khoben/telemirror#17]
hi khoben ,
please make filter & replace for exceptions for multiple words.for exam if find value-a in post descriptions can replace with custom one & can set multi env value for multiple values replacement.
for expert mode if you can set ( must have word/must not have ) mode for can be repost in destination channel , it's so much useful.
it means in must have mode , must in post description find value1 & if can't find bypass that post for repost & vice versa for must not have mode.
waiting for your changes commits :)
finest regards
goodbye

**Comment by khoben** [comment]
Hi, @claimclone
If I understand you correctly, you want to suggest:
1. White / black list of words, if they are in the message then repost / do not
2. Dictionary with word replacement
Pls correct me if I misunderstood anything
