### ISSUE TITLE
Пара вопросов по функционалу

### ISSUE THREAD

**Issue by Delave-las-Kure** [khoben/telemirror#25]
Здравствуйте. Хотел бы попробовать вашу библиотеку для пересылки сообщений из своего закрытого канала в публичный. На основе этого у меня есть пара вопросов:
1. Есть ли в планах ввести настройку задержки между публикациями сообщений?
2. Реализованы ли у вас какие-нибудь механизмы уменьшения риска бана? Я пробовал несколько других библиотек и через определенное время номер улетал в бан. Хоть номер и восстанавливали, но часто испытывать поддержку тг не хочется.  Номер участвовавший в тесте старый, плотность сообщений в группе не высокая, но иногда интервал между сообщениями может быть меньше 2-3 минут.

**Comment by khoben** [comment]
Здравствуйте, @Delave-las-Kure

Фактически нет причин для бана аккаунтов, вы просто шлёте сообщения, точно также как в приложениях телеграм.

Насчёт задержки -- телеграм пришлёт ошибку FloodWaitError с необходимым временем ожидания при частых запросах, но для этого надо ещё постараться, 2-3 минуты между сообщениями это довольно много для того, чтобы считать вас спамером.

Я не утверждаю, что бан полностью исключен, но у меня уже 3ий год работает аккаунт, который пересылает  ~500 сообщений в день.

**Comment by Delave-las-Kure** [comment]
Спасибо за ответ,
Я тоже считал что не должно быть каких-либо проблем ведь спама нет, да и каналы мои. Ошибка FloodWaitError никогда не появлялась. Но тем не менее тг почему-то решил отвешивать бан и непонятно с чем это связано.
Посмотрел ветку issues telethon и tdlib и там действительно пишут о возможности бана, а у некоторых бан перманентный.
Попробую вашу библиотеку на неделе, может все получится.
