### ISSUE TITLE
[Feature] replace a word

### ISSUE THREAD

**Issue by zdrigo171** [khoben/telemirror#28]
a function to change specific words, example, in the message I forwarded had the word "flowers" and I want to change this word "flowers" to "hello

**Comment by khoben** [comment]
Hello @zdrigo171 
Can you describe in what specific cases it can be used?

This is not difficult to implement, you need to make a [custom filter](https://github.com/khoben/telemirror/blob/21e8343f4b39acc74410b08450fbc2aa5ac8e238/telemirror/messagefilters.py#L11) that replaces the words in the message and pass it to the [constructor](https://github.com/khoben/telemirror/blob/21e8343f4b39acc74410b08450fbc2aa5ac8e238/main.py#L34). Feel free to fork.
