### ISSUE TITLE
can i deploy on heroku ?

### ISSUE THREAD

**Issue by NEOIR** [khoben/telemirror#3]
How can setup this on Heroku ?

Thanks

**Comment by khoben** [comment]
Hello, @NEOIR 
I have described two possible deployment options below:
https://github.com/khoben/telemirror#heroku

**Comment by NEOIR** [comment]
Hi

Im Deployed on Heroku.
How can get SESSION_STRING ? ( When i Run python login.py on app console not send any code to my number or telegram )
How to give SESSION_STRING ?

Thanks Bro

**Comment by khoben** [comment]
> Hi
> 
> Im Deployed on Heroku.
> How can get SESSION_STRING ? ( When i Run python login.py on app console not send any code to my number or telegram )
> How to give SESSION_STRING ?
> 
> Thanks Bro

Just tried it myself, everything is fine. Maybe you should run login.py locally and copy the token.
Also check if the phone number is correct and try again.
