### ISSUE TITLE
string session

### ISSUE THREAD

**Issue by bhbmalka** [khoben/telemirror#32]
how to get string session?
im not understand after try manytimes

**Comment by khoben** [comment]
Try to run [login.py](login.py) with your _app_id_ and _api_hash_. If authorization was successful it will print **SESSION_KEY**.

**Comment by madlifer** [comment]
let's make this thing simpler    use this： https://replit.com/@TeamUltroid/UltroidStringSession

@khoben

**Comment by khoben** [comment]
> let's make this thing simpler. use this： https://replit.com/@TeamUltroid/UltroidStringSession

@madlifer
Didn't see a difference, except for waiting for input from the console. Would you like to add input?
`API_ID` and `API_HASH` will have to be put into `.env` anyway.
