### ISSUE TITLE
How do I not send messages that words from a blacklist?

### ISSUE THREAD

**Issue by mthsfurio** [khoben/telemirror#35]
How do I not send messages that words from a blacklist?

blacklist = ball 
message "you kicked my ball"

channel > filter all text > if all ok > send
channel > filter all text > if not ok > ignore (**on example above**)

**Comment by khoben** [comment]
Fork the repository and check `event.message.message` for blacklisted words just before sending to the mirror channel (https://github.com/khoben/telemirror/blob/master/telemirror/mirroring.py#L37).
