### ISSUE TITLE
Clone Reply

### ISSUE THREAD

**Issue by sid8840** [khoben/telemirror#40]
hi,
The idea of mirroring is very good.
I am specially looking for a Clone Reply feature.in the latest version of telemirror,
Suppose the original channel sends a message then receiver gets a new message.
but when original channel reply's to that message, Receiver gets a new message instead of reply to prior message.

is there any option for that??

**Comment by khoben** [comment]
Hi, I already thought about it, but there were no cases where it was necessary. Most likely replay cloning will be released with the next update.

**Comment by khoben** [comment]
Hi, I already thought about it, but there were no cases where it was necessary. Most likely replay cloning will be released with the next update.

**Comment by sid8840** [comment]
> Hi, I already thought about it, but there were no cases where it was necessary. Most likely replay cloning will be released with the next update.

thanks for prompt reply
another thing is, cant we send chats from channel/group to user?
channel to channel is working flawlessly but error comes up at channel to user case.

**Comment by khoben** [comment]
> another thing is, cant we send chats from channel/group to user

In general, everything should work the same as with channels, the only thing for user chats is an identifier without -100 prefix.

**Comment by khoben** [comment]
Feel free to open a new issue if there are any problems.

**Comment by sid8840** [comment]
> Feel free to open a new issue if there are any problems.

hi,
when i remove -100 prefix for user chat, the main.py just flashes and exits itself.

**Comment by khoben** [comment]
> > Feel free to open a new issue if there are any problems.
> 
> hi, when i remove -100 prefix for user chat, the main.py just flashes and exits itself.
> 
> CHAT_MAPPING=[-100175****324:16*****472];

Exactly, identifiers are expected to be prefixed with -100. As a quick fix, you can change regex to `\[?((?:-?\d+,?)+):((?:-?\d+,?)+)\]?` from [here](https://github.com/khoben/telemirror/blob/master/config.py#L21).

**Comment by sid8840** [comment]
> > > Feel free to open a new issue if there are any problems.
> > 
> > 
> > hi, when i remove -100 prefix for user chat, the main.py just flashes and exits itself.
> > CHAT_MAPPING=[-100175****324:16*****472];
> 
> Exactly, identifiers are expected to be prefixed with -100. As a quick fix, you can change regex to `\[?((?:-?\d+,?)+):((?:-?\d+,?)+)\]?` from [here](https://github.com/khoben/telemirror/blob/master/config.py#L21).

as a quick fix, I have changed `\[?((?:-100\d+,?)+):((?:-100\d+,?)+)\]? to `\[?((?:-100\d+,?)+):((?:-?\d+,?)+)\]? and its working for channel to user now.

sorry to disturb  you on a very silly point but I got question regarding "Saving restricted Content".
you have already mentioned in your Readme about it but I am getting hiccups at that point.

I have channel_send to send only text chats to user. but when I turn on "Restrict saving content" , the script shows error. I don't have any media files to forward but only text to be forwarded with "restricted Saving content" condition.

**Comment by sid8840** [comment]
> Hi, I already thought about it, but there were no cases where it was necessary. Most likely replay cloning will be released with the next update.

Reply Cloning Work flawlessly with channel to user

**Comment by khoben** [comment]
> I have channel_send to send only text chats to user. but when I turn on "Restrict saving content" , the script shows error. I don't have any media files to forward but only text to be forwarded with "restricted Saving content" condition.

Text messages will be sent as in the usual case, but not with any media. To get around this, I made an unimplemented `RestrictSavingContentBypassFilter` which should re-save the medias and send the message with that medias. But its implementation has a lot of nuances (files can be very big, etc) and will generally slow down forwarding.

At the moment, `RestrictSavingContentBypassFilter` does not work and only text messages will be forwarded in chats with restriction enabled.

**Comment by khoben** [comment]
In general, this is not handled in any way and frequent errors in forwarding "restricted content" can lead to bans.

**Comment by madlifer** [comment]
> Hi, I already thought about it, but there were no cases where it was necessary. Most likely replay cloning will be released with the next update.

People use reply to rate an item, and after someone has used the item and posted a review, others will check it out to avoid making another purchase themselves.

So I think this feature still makes sense, hope you can add it to your consideration list

**Comment by khoben** [comment]
> > Hi, I already thought about it, but there were no cases where it was necessary. Most likely replay cloning will be released with the next update.
> 
> People use reply to rate an item, and after someone has used the item and posted a review, others will check it out to avoid making another purchase themselves.
> 
> So I think this feature still makes sense, hope you can add it to your consideration list

@madlifer 
Replies to post should already be cloned, check out the latest version in the master branch. 
If you mean comments on posts, you have to copy posts from the channel to your channel and from the linked chat to your comment chat.
