### ISSUE TITLE
Facing AttributeError

### ISSUE THREAD

**Issue by ThatDevCoder** [khoben/telemirror#46]
Hi, I'm currently testing forwards from channel to channel,
Whenever I try to test it by sending a message I get this error

`INFO:__main__:Channel mirroring has started with config:
Mirror mapping: 
-1001748000891 -> -1001621765064
Message deleting: Enabled
Message editing: Enabled
Installed message filter: ForwardFormatFilter
Using database: InMemoryDatabase

ERROR:telethon.client.updates:Unhandled exception on on_new_message
Traceback (most recent call last):
  File "/home/xyz/.local/lib/python3.9/site-packages/telethon/client/updates.py", line 454, in _dispatch_update
    await callback(event)
  File "/home/xyz/Desktop/telemirror/telemirror/mirroring.py", line 24, in on_new_message
    if event.message.chat.noforwards:
AttributeError: 'Channel' object has no attribute 'noforwards'`

**Comment by khoben** [comment]
@ThatDevCoder Have you solved the problem?
`Chat` or `Channel` objects should always have the `noforwards` flag, if there was a special case here please describe it.
