### ISSUE TITLE
Problem with mirror.config.yml 

### ISSUE THREAD

**Issue by qtozdec** [khoben/telemirror#50]
ru.
В примере указана переменная targets, которая по идее не должна быть обязательна.
При её удалении в цикле обработки конфига возникает ошибка.
eng.
The example specifies the variable targets, which in theory should not be required.
When it is deleted, an error occurs in the config processing cycle.

**Comment by khoben** [comment]
Thanks for the opening issue. 
Of course `targets` should be an optional field, check the latest changes in the repository.
