### ISSUE TITLE
Docker Porting

### ISSUE THREAD

**Issue by sid8840** [khoben/telemirror#58]
Any way to use this great utility on docker?
I am planning to use it on my synology nas Docker.

**Comment by khoben** [comment]
@sid8840 Yep
You can now run it within docker container, check latest changes (74a150fbb41c33ad285e0ef244b2d72c3c41a9dc)

**Comment by sid8840** [comment]
> @sid8840 Yep You can now run it within docker container, check latest changes ([74a150f](https://github.com/khoben/telemirror/commit/74a150fbb41c33ad285e0ef244b2d72c3c41a9dc))

Can you provide steps to deploy on Synology?

**Comment by khoben** [comment]
> Can you provide steps to deploy on Synology?

Actually no, I've never dealt with it. I think you need to find a guide on how to use the dockerized apps with Synology.

**Comment by sid8840** [comment]
> > Can you provide steps to deploy on Synology?
> 
> Actually no, I've never dealt with it. I think you need to find a guide on how to use the dockerized apps with Synology.

I am able to deploy via container. working flawlessly.
