### ISSUE TITLE
Offering new bot features.

### ISSUE THREAD

**Issue by qtozdec** [khoben/telemirror#59]
Было бы здорово реализовать gui добавление/удаление каналов из конфига. В качестве места обработки команд можно использовать сообщения с самим собой. В совершенстве это может быть реализовано с помощью бота, в котором было бы инлайн меню и который был бы связан с юзерботом. Также жду предложенной ранее функции фильтрации повторных сообщений. Готов внести пожертвование ради таких "премиум" функций

**Comment by khoben** [comment]
Предложенный функционал выходит за рамки моих нужд, поэтому вряд-ли появится в репозитории в ближайшем будущем. Поэтому единственные варианты это попробовать самому реализовать (может даже сделать пулл реквест), либо написать мне на почту ваш бюджет и требования к функционалу.
