### ISSUE TITLE
Error deleting a message

### ISSUE THREAD

**Issue by qtozdec** [khoben/telemirror#63]
```
telemirror_1  | Traceback (most recent call last):
telemirror_1  |   File "/app/telemirror/mirroring.py", line 196, in on_edit_message
telemirror_1  |     await self.edit_message(
telemirror_1  |   File "/usr/local/lib/python3.11/site-packages/telethon/client/messages.py", line 1212, in edit_message
telemirror_1  |     msg = self._get_response_message(request, await self(request), entity)
telemirror_1  |                                               ^^^^^^^^^^^^^^^^^^^
telemirror_1  |   File "/usr/local/lib/python3.11/site-packages/telethon/client/users.py", line 30, in __call__
telemirror_1  |     return await self._call(self._sender, request, ordered=ordered)
telemirror_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
telemirror_1  |   File "/usr/local/lib/python3.11/site-packages/telethon/client/users.py", line 84, in _call
telemirror_1  |     result = await future
telemirror_1  |              ^^^^^^^^^^^^
telemirror_1  | telethon.errors.rpcerrorlist.MessageNotModifiedError: Content of the message was not modified (caused by EditMessageRequest)
```

При любом удаленном сообщении в логах докера срабатывает traceback, но сообщение всё равно удаляется.

**Comment by khoben** [comment]
> ```
> telemirror_1  | Traceback (most recent call last):
> telemirror_1  |   File "/app/telemirror/mirroring.py", line 196, in on_edit_message
> telemirror_1  |     await self.edit_message(
> telemirror_1  |   File "/usr/local/lib/python3.11/site-packages/telethon/client/messages.py", line 1212, in edit_message
> telemirror_1  |     msg = self._get_response_message(request, await self(request), entity)
> telemirror_1  |                                               ^^^^^^^^^^^^^^^^^^^
> telemirror_1  |   File "/usr/local/lib/python3.11/site-packages/telethon/client/users.py", line 30, in __call__
> telemirror_1  |     return await self._call(self._sender, request, ordered=ordered)
> telemirror_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> telemirror_1  |   File "/usr/local/lib/python3.11/site-packages/telethon/client/users.py", line 84, in _call
> telemirror_1  |     result = await future
> telemirror_1  |              ^^^^^^^^^^^^
> telemirror_1  | telethon.errors.rpcerrorlist.MessageNotModifiedError: Content of the message was not modified (caused by EditMessageRequest)
> ```
> 
> При любом удаленном сообщении в логах докера срабатывает traceback, но сообщение всё равно удаляется.

Исходя из логов, ошибка в том, что редактируется сообщение без каких-либо изменений. Такое иногда может происходить при использовании фильтров (текст в источнике изменился, а в целевом канале остался прежним после обработки фильтрами) или, возможно, телеграм повторно шлет обновление которое уже обработано.
