### ISSUE TITLE
[HELP] Skip restricted  content

### ISSUE THREAD

**Issue by lucag74** [khoben/telemirror#68]
HI, 
thank's for your work, 
I enable the forward of restrict channel.
i uncommented this 

**Skip 'restricted saving content' enabled  
on event on_new_message**

there is a way for this channel mirror only the text , maybe the image (saving to array) ? 
(i see one old  post)

I can skip all the other element , audio, album etc.. ?
In few word i'm try to avoid the ban, and i'm interested on only text part and maybe images of every message.

Thank's

**Comment by khoben** [comment]
@lucag74 in general, you need to download, upload and change the media object.
Pseudo-code:
```python
# If here is media and noforwards enabled
if message.chat.noforwards and message.media:
    # Handle images
    if isinstance(message.media, types.MessageMediaPhoto):
        client: TelegramClient = message.client
        photo: bytes = await client.download_media(message=message, file=bytes)
        cloned_photo: types.TypeInputFile = client.upload_file(photo)
        message.media = cloned_photo
    # Others media types set to None (remove from original message)...
    else:
        message.media = None
```

**Comment by lucag74** [comment]
Fantastic i will try.

Your project it's fantastic and i'm using it and the same time i will level up my python and telegram skill :)

**Comment by Amiinnetdz** [comment]
Hi, anyone fixed that ? i am stil getting "are not supported"

**Comment by khoben** [comment]
> Hi, anyone fixed that ? i am stil getting "are not supported" 

Copying from protected channels isn't implemented because this violates the terms of the user agreement.
But you can implement it by yourself, check https://github.com/khoben/telemirror/issues/98#issuecomment-2014593520

**Comment by Amiinnetdz** [comment]
> > Hi, anyone fixed that ? i am stil getting "are not supported"
> 
> Copying from protected channels isn't implemented because this violates the terms of the user agreement. But you can implement it by yourself, check [#98 (comment)](https://github.com/khoben/telemirror/issues/98#issuecomment-2014593520)

root@racknerd-26e862:~/frd# python3.10 main.py
Traceback (most recent call last):
  File "/root/frd/main.py", line 3, in <module>
    from telemirror.mirroring import Telemirror
  File "/root/frd/telemirror/mirroring.py", line 9, in <module>
    from config import DirectionConfig
  File "/root/frd/config.py", line 11, in <module>
    from telemirror.messagefilters import (
  File "/root/frd/telemirror/messagefilters/__init__.py", line 3, in <module>
    from .restrictsavingfilter import RestrictSavingContentBypassFilter  # noqa: F401
  File "/root/frd/telemirror/messagefilters/restrictsavingfilter.py", line 13
    photo: bytes = await client.download_media(message=message, file=bytes)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: 'await' outside function

**Comment by khoben** [comment]
> Hi, anyone fixed that ? i am stil getting "are not supported"

Saw your message with error, indentation is most likely the problem there. Here is a sample filter implementation:
```python
from typing import Tuple, Type

from ..hints import EventMessage, EventLike
from .base import MessageFilter


class RestrictSavingContentBypassFilter(MessageFilter):
    """Filter that bypasses `saving content restriction`

    Sample implementation:

    Download the media, upload it to the Telegram servers,
    and then change to the new uploaded media

    ```
    # If here is media and noforwards enabled
    if message.chat.noforwards and message.media:
        # Handle images
        if isinstance(message.media, types.MessageMediaPhoto):
            client: TelegramClient = message.client
            photo: bytes = await client.download_media(message=message, file=bytes)
            cloned_photo: types.TypeInputFile = await client.upload_file(photo)
            message.media = cloned_photo
        # Others media types set to None (remove from original message)...
        else:
            message.media = None

    return True, message
    ```
    """

    @property
    def restricted_content_allowed(self) -> bool:
        return True

    async def _process_message(
        self, message: EventMessage, event_type: Type[EventLike]
    ) -> Tuple[bool, EventMessage]:
        
        if message.media is None or (
            message.chat is None or not message.chat.noforwards
        ):
            # Forwarding allowed
            return True, message
        
        client: TelegramClient = message.client
        
        # Handle images
        if isinstance(message.media, types.MessageMediaPhoto):
            photo: bytes = await client.download_media(message=message, file=bytes)
            cloned_photo: types.TypeInputFile = await client.upload_file(photo)
            message.media = cloned_photo
        # Others media types set to None (remove from original message)...
        else:
            message.media = None

        # Process message if not empty
        return bool(message.media or message.message), message
```

**Comment by Amiinnetdz** [comment]
> > Hi, anyone fixed that ? i am stil getting "are not supported"
> 
> Saw your message with error, indentation is most likely the problem there. Here is a sample filter implementation:
> 
> ```python
> from typing import Tuple, Type
> 
> from ..hints import EventMessage, EventLike
> from .base import MessageFilter
> 
> 
> class RestrictSavingContentBypassFilter(MessageFilter):
>     """Filter that bypasses `saving content restriction`
> 
>     Sample implementation:
> 
>     Download the media, upload it to the Telegram servers,
>     and then change to the new uploaded media
> 
>     ```
>     # If here is media and noforwards enabled
>     if message.chat.noforwards and message.media:
>         # Handle images
>         if isinstance(message.media, types.MessageMediaPhoto):
>             client: TelegramClient = message.client
>             photo: bytes = await client.download_media(message=message, file=bytes)
>             cloned_photo: types.TypeInputFile = await client.upload_file(photo)
>             message.media = cloned_photo
>         # Others media types set to None (remove from original message)...
>         else:
>             message.media = None
> 
>     return True, message
>     ```
>     """
> 
>     @property
>     def restricted_content_allowed(self) -> bool:
>         return True
> 
>     async def _process_message(
>         self, message: EventMessage, event_type: Type[EventLike]
>     ) -> Tuple[bool, EventMessage]:
>         
>         if message.media is None or (
>             message.chat is None or not message.chat.noforwards
>         ):
>             # Forwarding allowed
>             return True, message
>         
>         client: TelegramClient = message.client
>         
>         # Handle images
>         if isinstance(message.media, types.MessageMediaPhoto):
>             photo: bytes = await client.download_media(message=message, file=bytes)
>             cloned_photo: types.TypeInputFile = await client.upload_file(photo)
>             message.media = cloned_photo
>         # Others media types set to None (remove from original message)...
>         else:
>             message.media = None
> 
>         # Process message if not empty
>         return bool(message.media or message.message), message
> ```

Hi added this but stil getting this message ?
WARNING 2024-05-25 14:43:50,223 [mirroring.py:117]:telemirror: Forwards from channel#-1001633397411 with `restricted saving content` enabled to channel#-1002063015567 are not supported.

**Comment by khoben** [comment]
> > > Hi, anyone fixed that ? i am stil getting "are not supported"
> > 
> > 
> > Saw your message with error, indentation is most likely the problem there. Here is a sample filter implementation:
> > ```python
> > from typing import Tuple, Type
> > 
> > from ..hints import EventMessage, EventLike
> > from .base import MessageFilter
> > 
> > 
> > class RestrictSavingContentBypassFilter(MessageFilter):
> >     """Filter that bypasses `saving content restriction`
> > 
> >     Sample implementation:
> > 
> >     Download the media, upload it to the Telegram servers,
> >     and then change to the new uploaded media
> > 
> >     ```
> >     # If here is media and noforwards enabled
> >     if message.chat.noforwards and message.media:
> >         # Handle images
> >         if isinstance(message.media, types.MessageMediaPhoto):
> >             client: TelegramClient = message.client
> >             photo: bytes = await client.download_media(message=message, file=bytes)
> >             cloned_photo: types.TypeInputFile = await client.upload_file(photo)
> >             message.media = cloned_photo
> >         # Others media types set to None (remove from original message)...
> >         else:
> >             message.media = None
> > 
> >     return True, message
> >     ```
> >     """
> > 
> >     @property
> >     def restricted_content_allowed(self) -> bool:
> >         return True
> > 
> >     async def _process_message(
> >         self, message: EventMessage, event_type: Type[EventLike]
> >     ) -> Tuple[bool, EventMessage]:
> >         
> >         if message.media is None or (
> >             message.chat is None or not message.chat.noforwards
> >         ):
> >             # Forwarding allowed
> >             return True, message
> >         
> >         client: TelegramClient = message.client
> >         
> >         # Handle images
> >         if isinstance(message.media, types.MessageMediaPhoto):
> >             photo: bytes = await client.download_media(message=message, file=bytes)
> >             cloned_photo: types.TypeInputFile = await client.upload_file(photo)
> >             message.media = cloned_photo
> >         # Others media types set to None (remove from original message)...
> >         else:
> >             message.media = None
> > 
> >         # Process message if not empty
> >         return bool(message.media or message.message), message
> > ```
> 
> Hi added this but stil getting this message ? WARNING 2024-05-25 14:43:50,223 [mirroring.py:117]:telemirror: Forwards from channel#-1001633397411 with `restricted saving content` enabled to channel#-1002063015567 are not supported.
> 
> my source containt Text and image

You should also add `RestrictSavingContentBypassFilter` to yaml filter config:
```yaml
...
directions:
  - from: [-1001]
    to: [-1002]
    filters:
      - RestrictSavingContentBypassFilter
```
To make the filter importable, add to `telemirror/messagefilters/__init__.py`:
```python
from .restrictsavingfilter import RestrictSavingContentBypassFilter  # noqa: F401
```

**Comment by Amiinnetdz** [comment]
message forwarded but image stil get this error ?!
ERROR 2024-05-25 15:16:12,865 [mirroring.py:54]:telemirror: name 'types' is not defined
Traceback (most recent call last):
  File "/root/frd/telemirror/mirroring.py", line 52, in wrapper
    return await fn(self, *args, **kw)
  File "/root/frd/telemirror/mirroring.py", line 125, in new_message
    proceed, filtered_message = await config.filters.process(
  File "/root/frd/telemirror/messagefilters/base.py", line 29, in process
    return await self._process_message(entity, event_type)
  File "/root/frd/telemirror/messagefilters/restrictsavingfilter.py", line 49, in _process_message
    if isinstance(message.media, types.MessageMediaPhoto):
NameError: name 'types' is not defined

**Comment by khoben** [comment]
> message forwarded but image stil get this error ?! ERROR 2024-05-25 15:16:12,865 [mirroring.py:54]:telemirror: name 'types' is not defined Traceback (most recent call last): File "/root/frd/telemirror/mirroring.py", line 52, in wrapper return await fn(self, *args, **kw) File "/root/frd/telemirror/mirroring.py", line 125, in new_message proceed, filtered_message = await config.filters.process( File "/root/frd/telemirror/messagefilters/base.py", line 29, in process return await self._process_message(entity, event_type) File "/root/frd/telemirror/messagefilters/restrictsavingfilter.py", line 49, in _process_message if isinstance(message.media, types.MessageMediaPhoto): NameError: name 'types' is not defined

Here is missing imports. See updated filter sample code https://github.com/khoben/telemirror/issues/68#issuecomment-2131271737

**Comment by Amiinnetdz** [comment]
all working good but one last problem image send as file 
![Capture d’écran 2024-05-25 172530](https://github.com/khoben/telemirror/assets/161169354/23aa89c3-c5c1-4f27-8850-9ab38c6f376c)
thank you for your help

**Comment by khoben** [comment]
> all working good but one last problem image send as file ![Capture d’écran 2024-05-25 172530](https://private-user-images.githubusercontent.com/161169354/333817839-23aa89c3-c5c1-4f27-8850-9ab38c6f376c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2OTE3OTIsIm5iZiI6MTcxNjY5MTQ5MiwicGF0aCI6Ii8xNjExNjkzNTQvMzMzODE3ODM5LTIzYWE4OWMzLWM1YzEtNGYyNy04ODUwLTlhYjM4YzZmMzc2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwMjQ0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDc2ZDc4NDQxYmJkY2EwOGNlZmUyNTIxYzk5ZWI1YTA0YmM0MjdmMzE0MzZjYzBkOGRmNGUyM2U4ODI0MzdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MsrT6ixEfUyVpiyPebRCji5Bq1cHUUGn0GjfF2njtlg) thank you for your help

I suppose setting a filename might help:
```python
cloned_photo.name = (
    message.file.name if message.file.name else "photo.jpg"
)
```
Also I've updated the example https://github.com/khoben/telemirror/issues/68#issuecomment-2131271737

**Comment by Amiinnetdz** [comment]
it work like a charme <3 thank you bro

**Comment by Amiinnetdz** [comment]
i will try to make it easy with web interface with streamlit can you suggest anything ?

**Comment by khoben** [comment]
> i will try to make it easy with web interface with streamlit can you suggest anything ?

I think it's a good idea to make a UI, someone might find it useful. You need to somehow save and modify the `chat_mapping` from https://github.com/khoben/telemirror/blob/master/telemirror/mirroring.py and the filter parameters from https://github.com/khoben/telemirror/tree/master/telemirror/messagefilters . Feel free to make a PR.
