### ISSUE TITLE
Как включить пересылку текста и медиа из приватных каналов?

### ISSUE THREAD

**Issue by ilyadzhan** [khoben/telemirror#71]
Как включить пересылку текста и медиа из приватных каналов? Где именно нужно поменять настройки и где добавить сохранение файла для последующей отправки?

**Comment by khoben** [comment]
Я так понимаю речь идёт о каналах с запретом на сохранение и пересылку?
Тогда необходимо реализовать специальный обработчик событий на этот случай https://github.com/khoben/telemirror/blob/master/telemirror/messagefilters/restrictsavingfilter.py (примерная реализация указана в аннотации к методу).
Добавить импорт в https://github.com/khoben/telemirror/blob/master/telemirror/messagefilters/__init__.py и в файле `mirror.config.yml` для канала приемника указать этот фильтр.

**Comment by ilyadzhan** [comment]
Все равно выводится warning:

Mirror mapping: 
-1001809912690 -> 1001539138995
Mirror targets config: {1001539138995: TargetConfig(disable_delete=False, disable_edit=False, filters=EmptyMessageFilter), -1001809912690: TargetConfig(disable_delete=False, disable_edit=False, filters=RestrictSavingContentBypassFilter)}
Using database: InMemoryDatabase

INFO  2023-02-20 18:37:36,955 [mirroring.py:37]:telemirror: [New message]: https://t.me/c/1809912690/62
WARNING 2023-02-20 18:37:36,955 [mirroring.py:52]:telemirror: Forwards from channel#-1001809912690 with `restricted saving content` enabled to channel#1001539138995 are not supported.

**Comment by khoben** [comment]
Фильтры нужно указывать для каналов, _в которые идет пересылка_:
```yaml
directions:
  - from: [-1001809912690]
    to: [-1001539138995]

targets:
  - id: -1001539138995
    filters:
      - RestrictSavingContentBypassFilter
```
