### ISSUE TITLE
how to forward previous messages 

### ISSUE THREAD

**Issue by anaschaudhary33** [khoben/telemirror#77]
It's works fine for forwarding of new messages. But how to forward previous messages. 
I want to forward all messages in a channel to another channel

**Comment by khoben** [comment]
You can use [telecopy.py](https://github.com/khoben/telemirror/blob/ee44adaaa320550ec86270fa57ee0677791cbf4e/telecopy.py) for creating full channel copy.

**Comment by anaschaudhary33** [comment]
Is it possible to forward message using a range of message ids?

**Comment by khoben** [comment]
See `limit`, `min_id` and `max_id` parameters in [client.iter_messages](https://docs.telethon.dev/en/stable/modules/client.html#telethon.client.messages.MessageMethods.iter_messages)
