### ISSUE TITLE
can you help me set it up ?

### ISSUE THREAD

**Issue by iamysfy** [khoben/telemirror#78]
please tell me if you can help set it up

**Comment by khoben** [comment]
> also, this
> INFO  2023-10-04 05:55:48,739 [mirroring.py:63]:telemirror: [New message]: https://t.me/c/1610399834/18
> ERROR 2023-10-04 05:55:48,907 [mirroring.py:113]:telemirror: Error while sending message to chat#-1001596098138. MessageEmptyError: Empty or invalid UTF-8 message was sent (caused by SendMessageRequest)
> INFO  2023-10-04 05:55:54,723 [mirroring.py:63]:telemirror: [New message]: https://t.me/c/1610399834/19
> ERROR 2023-10-04 05:55:54,810 [mirroring.py:113]:telemirror: Error while sending message to chat#-1001596098138. MessageEmptyError: Empty or invalid UTF-8 message was sent (caused by SendMessageRequest)

Can you send your config and a link to the public channel with this message?

**Comment by khoben** [comment]
I can't help you without the message that causes the error. You can create a public channel with this message and send the link here. Also please send your config without credentials.
