### ISSUE TITLE
SkipWithKeywordsFilter

### ISSUE THREAD

**Issue by ipl-adm** [khoben/telemirror#79]
How currently this feature writes in config?
Also, maybe create fully exampled referenced configuration?

**Comment by khoben** [comment]
Here's an example for `SkipWithKeywordFilter`: https://github.com/khoben/telemirror/issues/60#issuecomment-1360510360

That's good idea to add examples for all filters. Actually you need to specify the filter name and pass parameters with same types but in yaml syntax.
