### ISSUE TITLE
Replace links in messages

### ISSUE THREAD

**Issue by ipl-adm** [khoben/telemirror#81]
How to replace links in telegram markdown formatted message?

**Comment by khoben** [comment]
There is no such filter for urls replacement now, `KeywordReplaceFilter` can be used to replace URLs like keywords. You can use `UrlMessageFilter` as a base for url replacement with mapping.

**Comment by khoben** [comment]
"markdown formatted message"

It doesn't matter, telegram sends an array with formatting entities.
