### ISSUE TITLE
Is it possible to forward a message only if the message contains specific keywords? 

### ISSUE THREAD

**Issue by KFCLB** [khoben/telemirror#83]
With SkipWithKeywordsFilter you can specify keywords and messages won't get forwarded if they contain those keywords. 

Is there an option to SkipWithOUTKeywordsFilter, where you have a list of keywords (whitelists) and if the message contains any of the keywords from whitelist only then it gets forwarded?

**Comment by khoben** [comment]
You have already written what needs to be done for such a filter: just invert the [expression](https://github.com/khoben/telemirror/blob/master/telemirror/messagefilters/messagefilters.py#L405) to `self._regex.search(message.message) is not None`
