### ISSUE TITLE
Heroku deployment issues: binding $PORT, pass filters configuration thru environment 

### ISSUE THREAD

**Issue by chakra1n** [khoben/telemirror#96]
### **Heroku web process failed to bind to $PORT within 60 seconds of launch:**

![image](https://github.com/khoben/telemirror/assets/147328344/4dc64b91-0c1f-45a3-b344-d094630725ff)

### **Feature Request:**
Include a feature to set **YAML file contents** directly via environment variables. This would streamline deployment on platforms like Heroku, eliminating the need for manual YAML file creation when the repository is cloned and made private.

**Comment by khoben** [comment]
Could you provide a minimal example and error stacktrace for the bugs found?
The screenshot shows that Heroku expects that the port specified through the `PORT` variable should be bound to the application, it will be added soon.

Configuring filters through environment vars will be too complicated. The only optimal option is to specify it via yaml/json string, which makes editing not very convenient.

**Comment by khoben** [comment]
@chakra1n  Please check if the app is now working on Heroku with the latest commit?

**Comment by chakra1n** [comment]
First two issues are fixed but third one is still there.

### Message at Source Side (before editing image)
![image](https://github.com/khoben/telemirror/assets/147328344/d9a7e2e6-c9ab-45d7-a5af-6a2b5ab3ccc7)

### Message at Destination Side (before editing image)
![image](https://github.com/khoben/telemirror/assets/147328344/4bb19715-91f1-4dae-b8b6-4d93c987c9ff)

**This works perfectly fine but check next scenario.**

### Image edited using telegram official image edit feature
![image](https://github.com/khoben/telemirror/assets/147328344/299e593b-fac8-4eef-af95-62b07627d217)

### Message at Source Side (after editing image)
![image](https://github.com/khoben/telemirror/assets/147328344/cebca8e9-5d1a-4ac2-a8b0-701d5cb1956f)

### Message at Destination Side (after editing image)
![image](https://github.com/khoben/telemirror/assets/147328344/c78ee791-4083-436e-a400-6b5cf2deb8a3)

**Image is not edited and also now app gets crashed**

### Heroku Logs
![image](https://github.com/khoben/telemirror/assets/147328344/16abf718-6f16-4381-bff5-c5885a506b7e)


Also I am not saying to configure filters via environment variables, instead I was saying to put YAML file contents same in one env var, as we need to first import your repo then make it private then setup yaml file. While forking, repo is always public so can't expose YAML config file publically. Also importing restricts us any future commits made to the original repo while forking one does.

**Comment by chakra1n** [comment]
> Configuring filters through environment vars will be too complicated. The only optimal option is to specify it via yaml/json string, which makes editing not very convenient.

I am not saying to configure filters via environment variables, instead I was saying to put YAML file contents same in one env var, as we need to first import your repo then make it private then setup yaml file. While forking, repo is always public so can't expose YAML config file publically. Also importing restricts us any future commits made to the original repo while forking one does.

**Comment by khoben** [comment]
> > Configuring filters through environment vars will be too complicated. The only optimal option is to specify it via yaml/json string, which makes editing not very convenient.
> 
> I am not saying to configure filters via environment variables, instead I was saying to put YAML file contents same in one env var, as we need to first import your repo then make it private then setup yaml file. While forking, repo is always public so can't expose YAML config file publically. Also importing restricts us any future commits made to the original repo while forking one does.
> 
> 
> 

You want to put the entire configuration from yaml into single string as environment variable. Okay, I got it.

**Comment by khoben** [comment]
> First two issues are fixed but third one is still there.
> 
> ### Message at Source Side (before editing image)
> ![image](https://github.com/khoben/telemirror/assets/147328344/d9a7e2e6-c9ab-45d7-a5af-6a2b5ab3ccc7)
> 
> ### Message at Destination Side (before editing image)
> ![image](https://github.com/khoben/telemirror/assets/147328344/4bb19715-91f1-4dae-b8b6-4d93c987c9ff)
> 
> **This works perfectly fine but check next scenario.**
> 
> ### Image edited using telegram official image edit feature
> ![image](https://github.com/khoben/telemirror/assets/147328344/299e593b-fac8-4eef-af95-62b07627d217)
> 
> ### Message at Source Side (after editing image)
> ![image](https://github.com/khoben/telemirror/assets/147328344/cebca8e9-5d1a-4ac2-a8b0-701d5cb1956f)
> 
> ### Message at Destination Side (after editing image)
> ![image](https://github.com/khoben/telemirror/assets/147328344/c78ee791-4083-436e-a400-6b5cf2deb8a3)
> 
> **Image is not edited and also now app gets crashed**
> 
> ### Heroku Logs
> ![image](https://github.com/khoben/telemirror/assets/147328344/16abf718-6f16-4381-bff5-c5885a506b7e)

Just checked replacing and editing images, everything works. Actually, from your logs you have the same problem with heroku port binding.

**Comment by khoben** [comment]
Try running the app locally, also check out the latest version

**Comment by chakra1n** [comment]
> Try running the app locally, also check out the latest version

Thanks, its working fine after re-deploying in Heroku. Now web app url is also giving status OK earlier it states Application Error.

> You want to put the entire configuration from yaml into single string as environment variable. Okay, I got it

Now, just waiting for this update :) 
It will be helpful for other users too who are using Heroku ..

**Comment by khoben** [comment]
Try setting `YAML_CONFIG_ENV` now. I assume you can just copy-paste the yaml file contents through the heroku interface.

**Comment by chakra1n** [comment]
> Try setting `YAML_CONFIG_ENV` now. I assume you can just copy-paste the yaml file contents through the heroku interface.

Thanks, its working. 

**ISSUE RESOLVED!!**
