### ISSUE TITLE
Not forwarding messages from deafult topic 

### ISSUE THREAD

**Issue by corpsepapi** [khoben/telemirror#98]
It's working fine with all the topics except the default one and when I'm only adding only the group id it's forwarding all topics in a single group topic

**Comment by khoben** [comment]
Please try now #1 for the default topic

**Comment by corpsepapi** [comment]
Hey, thank you for resolving this issue I wanted to ask u one more thing while forwarding messages from groups is it possible to forward the original message sender's username too?

**Comment by khoben** [comment]
> Hey, thank you for resolving this issue I wanted to ask u one more thing while forwarding messages from groups is it possible to forward the original message sender's username too? 

There are two options here: don't copy, but forward (mode option), or use `ForwardFormatFilter` (set filter in yaml configuration).

**Comment by corpsepapi** [comment]
i tried forward mode but the replies don't work in it, is it possible to get usernames in a specific channel using copy mode?

**Comment by khoben** [comment]
> i tried forward mode but the replies don't work in it, is it possible to get usernames in a specific channel using copy mode?

If you need to forward from a chat, you will need to create a filter like https://github.com/khoben/telemirror/blob/master/telemirror/messagefilters/messagefilters.py#L213, but instead of `channel_name` (https://github.com/khoben/telemirror/blob/master/telemirror/messagefilters/messagefilters.py#L253) get the user name from the `message` object.

Getting username from `message`:
```python
message_sender = await message.get_sender()
message_sender_name = utils.get_display_name(message_sender)
```

**Comment by khoben** [comment]
Check updates to [ForwardFormatFilter](https://github.com/khoben/telemirror/blob/master/telemirror/messagefilters/messagefilters.py#L222)

Sample configuration:
```yaml
directions:
  - from: [-1001#3]
    to: [-1002#1]
    filters:
      - ForwardFormatFilter:
          format: "{sender_title} {sender_username} says:\n\n{message_text}"
```

**Comment by corpsepapi** [comment]
working, thank you so much <3<3

**Comment by corpsepapi** [comment]
Hey khoen, sorry to diusturb you again. I'm using this restricted channel filter `class RestrictSavingContentBypassFilter(MessageFilter):
    def __init__(self, send_restricted_content=True):
        self.send_restricted_content = send_restricted_content

    async def _process_message(
        self, message: EventMessage, event_type: Type[EventLike]
    ) -> Tuple[bool, EventMessage]:
        if message.chat.noforwards and message.media:
            # Handle images
            
            if isinstance(message.media, types.MessageMediaPhoto):
                client: TelegramClient = message.client
                photo: bytes = await client.download_media(message=message, file=bytes)
                cloned_photo: types.TypeInputFile = await client.upload_file(photo)
                message.media = cloned_photo
            # Others media types set to None (remove from original message)...
            else:
                message.media = None

        return True, message`
        
        to forward messages from restricted channels or groups but when someone in restricted group topics sends an image its sends this error  `ERROR 2024-03-07 00:43:03,782 [mirroring.py:175]:telemirror: Error while sending message to chat#-1002068277802. ChatForwardsRestrictedError: You can't forward messages from a protected chat (caused by SendMediaRequest)` texts are being forwarded but no the attachments in group topics

**Comment by khoben** [comment]
Try logging the line where the media should be downloaded and replaced. More likely "if" gives `False` in your case.

**Comment by corpsepapi** [comment]
still couldn't figure it out, could u help me with what I'm doing wrong?

**Comment by khoben** [comment]
Can you show your config and the changes you made?

**Comment by corpsepapi** [comment]
I added the restricted filter in messagefilter.py and 

class MessageFilter(Protocol):
    @property
    def restricted_content_allowed(self) -> bool:
        """Indicates that restricted content is allowed or not to process"""
        return True
         and changes this to true

**Comment by khoben** [comment]
Just checked, everything works. To begin with, I want to say that forwarding from channels where this is prohibited violates the Telegram Terms of Service.
But for testing purposes you should change the [`_process_message`](https://github.com/khoben/telemirror/blob/master/telemirror/messagefilters/restrictsavingfilter.py#L36) method to [sample implementation from docstring](https://github.com/khoben/telemirror/blob/master/telemirror/messagefilters/restrictsavingfilter.py#L17C5-L28C25) and then use the `RestrictSavingContentBypassFilter` filter in the config.
To make the filter importable, add to `telemirror/messagefilters/__init__.py`:
```python
from .restrictsavingfilter import RestrictSavingContentBypassFilter  # noqa: F401
```

**Comment by corpsepapi** [comment]
Thank you for the help it worked but, its sending images as file 
![image](https://github.com/khoben/telemirror/assets/85352643/9a827f03-0497-460c-a337-a1f8f92518e3)

**Comment by khoben** [comment]
> Thank you for the help it worked but, its sending images as file 
> ![image](https://github.com/khoben/telemirror/assets/85352643/9a827f03-0497-460c-a337-a1f8f92518e3)
> 

You can try to wrap downloaded bytes with:

```python
message.media = types.InputMediaUploadedPhoto(cloned_media)
```

**Comment by corpsepapi** [comment]
Now I'm getting this error: PhotoExtInvalidError: The extension of the photo is invalid (caused by SendMediaRequest)

**Comment by khoben** [comment]
Haven't tested it, but maybe taking the file name from the source message could help:
```python
cloned_photo: types.TypeInputFile = await client.upload_file(photo, file_name=message.file.name)
message.media = types.InputMediaUploadedPhoto(file=cloned_photo)
```

**Comment by corpsepapi** [comment]
Still getting the same error

**Comment by khoben** [comment]
In what environment is the program running? OS/docker, python version and through which telegram client are messages with images sent?

**Comment by khoben** [comment]
It would also be great if you sent the images themselves as files here

**Comment by corpsepapi** [comment]
> In what environment is the program running? OS/docker, python version and through which telegram client are messages with images sent?
Windows OS
Python Version: 3.12.2

**Comment by khoben** [comment]
Really idk why images are sent like random files or with error. Couldn't get the same behavior. Try running via docker or check that all dependencies are updated: `pip install -r requirements.txt`

**Comment by Amiinnetdz** [comment]
Hi did you fix that ?

**Comment by khoben** [comment]
@corpsepapi You may try to specify the `name` for `cloned_photo` if it is still relevant for you https://github.com/khoben/telemirror/issues/68#issuecomment-2132041731

**Comment by khoben** [comment]
> I get this error after few time 
> Error handling request
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_protocol.py", line 3
> 50, in data_received
>     messages, upgraded, tail = self._request_parser.feed_data(data)
>   File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.
> feed_data
> aiohttp.http_exceptions.BadStatusLine: 400, message:
>   Invalid method encountered:
>     b'\x16\x03\x01'
>       ^

`aiohttp` is used here for the heartbeat endpoint, someone from outside is sending invalid packets.
This should not affect the forwarding process in any way.

**Comment by Amiinnetdz** [comment]
I have a question how to forward voice & video the bot copy only message text and photo, i am using bypass restrict content. Thank you

**Comment by khoben** [comment]
> I have a question how to forward voice & video the bot copy only message text and photo, i am using bypass restrict content. Thank you

https://github.com/khoben/telemirror/issues/123#issuecomment-2316563356
